### ISSUE TITLE
Error Running

### ISSUE THREAD

**Issue by smolz** [michaelarnauts/cec-mqtt-bridge#3]
Initialising CEC...
Initialising IR...
Initialising MQTT...
Traceback (most recent call last):
  File "bridge.py", line 263, in <module>
    mqtt_client.connect(config['mqtt']['broker'], config['mqtt']['port'], 60)
  File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 685, in connect
    self.connect_async(host, port, keepalive, bind_address)
  File "/usr/local/lib/python3.4/dist-packages/paho/mqtt/client.py", line 741, in connect_async
    if port <= 0:
TypeError: unorderable types: str() <= int()

**Comment by michaelarnauts** [comment]
Have you configured the mqtt port correctly in `config.ini`? Could it be empty?
